CMSettingsProvider: Fix instance of provider class
By mistake, the provider remote was changed, causing an NPE of
CMSettingsProvider:

java.lang.RuntimeException: Unable to get provider
org.cyanogenmod.cmsettings.SettingsExtProvider:
java.lang.ClassNotFoundException: Didn't find class
"org.cyanogenmod.cmsettings.SettingsExtProvider"

SettingsExtProvider, must remain CMSettingsProvider. The string may
diff, but the class causes boot failure

Change-Id: I5a9a28fed697bf74671c1e076f36226cd0711e65